name: Build for all platforms

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.27'
      - name: Build all binaries
        run: ./build_all.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: otpgo-binaries
          path: build
          if-no-files-found: error
